### ISSUE TITLE
'package.swift' is using Swift tools version 3.1.0 which is no longer supported

### ISSUE THREAD

**Issue by kiddden** [kreatimont/google-analytics-ios-sdk-spm#2]
When trying to add your package Xcode says:
Package 'package.swift' is using Swift tools version 3.1.0 which is no longer supported; consider using '// swift-tools-version: 5.8' to specify the current tools version

**Comment by kreatimont** [comment]
@kiddden thanks for the report! Try adding with **Dependency Rule** set to the `master` branch.

**Comment by vvit** [comment]
The fix works so the issue can be closed. 👍

**Comment by kreatimont** [comment]
Fixed ✅
